name: CI

on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/setup-node@v4 # It's a reference to... not a local file

      - name: Setup Node
        uses: actions/checkout@v4
        with:
          node-version: 24
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with: 
          version: 11.10.0
      
      - name: Install dependencies
        run: pnpm install